# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:3.22
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# install typical php packages and then additional packages
RUN apk add --no-cache bash bind-tools imagemagick imagemagick-svg openssl php82 php82-bcmath php82-bz2 php82-ctype php82-curl php82-exif php82-fileinfo php82-gd php82-fpm php82-gettext php82-gmp php82-iconv php82-intl php82-imap php82-json php82-ldap php82-mbstring php82-mysqli php82-opcache php82-pecl-apcu php82-pecl-igbinary php82-pecl-imagick php82-pecl-mcrypt php82-pecl-memcached php82-pecl-redis php82-pdo php82-pdo_mysql php82-pdo_pgsql php82-phar php82-pgsql php82-pcntl php82-posix php82-simplexml php82-sodium php82-sysvsem php82-xml php82-xmlreader php82-xmlwriter php82-zip ssmtp wget whois &&\
  (deluser "$(grep ':33:' /etc/passwd | awk -F ':' '{print $1}')" || true) &&\
  (delgroup "$(grep '^www-data:' /etc/group | awk -F ':' '{print $1}')" || true) &&\
  mkdir /var/www &&\
  addgroup -g 33 www-data &&\
  adduser -D -u 33 -G www-data -s /sbin/nologin -H -h /var/www www-data &&\
  chown -R www-data:www-data /var/www &&\
  ln -sf /usr/bin/php82 /usr/bin/php &&\
  echo 'include=/etc/php82/php-fpm.d/www.inc' >> /etc/php82/php-fpm.d/www.conf

# add entrypoint script
COPY entrypoint.sh /entrypoint.sh

# add logging config
COPY logging.conf /etc/php83/php-fpm.d/logging.conf

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm82","-F","--fpm-config","/etc/php82/php-fpm.conf"]
