# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:latest
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# install typical php packages and then additional packages
RUN apk add --no-cache bind-tools imagemagick imagemagick-svg openssl php83 php83-bcmath php83-bz2 php83-ctype php83-curl php83-exif php83-fileinfo php83-gd php83-fpm php83-gettext php83-gmp php83-iconv php83-intl php83-imap php83-json php83-ldap php83-mbstring php83-mysqli php83-opcache php83-pecl-apcu php83-pecl-igbinary php83-pecl-imagick php83-pecl-memcached php83-pecl-redis php83-pdo php83-pdo_mysql php83-pdo_pgsql php83-phar php83-pgsql php83-pcntl php83-posix php83-simplexml php83-sodium php83-sysvsem php83-xml php83-xmlreader php83-xmlwriter php83-zip ssmtp wget whois &&\
  apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing php83-pecl-mcrypt &&\
  sed -i "s#listen = 127.0.0.1:9000#listen = /var/run/php/php-fpm81.sock#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#^user = nobody#user = www-data#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#^group = nobody#group = www-data#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.owner = nobody#listen.owner = www-data#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.group = nobody#listen.group = www-data#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.mode = 0660#listen.mode = 0660#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#^;env#env#g" /etc/php83/php-fpm.d/www.conf &&\
  sed -i "s#upload_max_filesize = 2M#upload_max_filesize = 8M#g" /etc/php83/php.ini &&\
  sed -i "s#^;opcache.enable=1#opcache.enable=1#g" /etc/php83/php.ini &&\
  sed -i "s#^;opcache.interned_strings_buffer=8#opcache.interned_strings_buffer=32#g" /etc/php83/php.ini &&\
  sed -i "s#^;opcache.max_accelerated_files=10000#opcache.max_accelerated_files=25000#g" /etc/php83/php.ini &&\
  sed -i "s#^;opcache.memory_consumption=128#opcache.memory_consumption=256#g" /etc/php83/php.ini &&\
  sed -i "s#^;opcache.save_comments=1#opcache.save_comments=1#g" /etc/php83/php.ini &&\
  sed -i "s#^;opcache.revalidate_freq=2#opcache.revalidate_freq=30#g" /etc/php83/php.ini &&\
  echo 'apc.enable_cli=1' >> /etc/php83/conf.d/apcu.ini &&\
  deluser "$(grep ':33:' /etc/passwd | awk -F ':' '{print $1}')" || true &&\
  delgroup "$(grep '^www-data:' /etc/group | awk -F ':' '{print $1}')" || true &&\
  mkdir /var/www &&\
  addgroup -g 33 www-data &&\
  adduser -D -u 33 -G www-data -s /sbin/nologin -H -h /var/www www-data &&\
  chown -R www-data:www-data /var/www &&\
  ln -sf /usr/bin/php83 /usr/bin/php

# add entrypoint script
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm83","-F","--fpm-config","/etc/php83/php-fpm.conf"]
