# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:latest
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# install typical php packages and then additional packages
RUN apk add --no-cache bash bind-tools imagemagick imagemagick-svg openssl php83 php83-bcmath php83-bz2 php83-ctype php83-curl php83-exif php83-fileinfo php83-gd php83-fpm php83-gettext php83-gmp php83-iconv php83-intl php83-imap php83-json php83-ldap php83-mbstring php83-mysqli php83-opcache php83-pecl-apcu php83-pecl-igbinary php83-pecl-imagick php83-pecl-memcached php83-pecl-redis php83-pdo php83-pdo_mysql php83-pdo_pgsql php83-phar php83-pgsql php83-pcntl php83-posix php83-simplexml php83-sodium php83-sysvsem php83-xml php83-xmlreader php83-xmlwriter php83-zip ssmtp wget whois &&\
  apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community php83-pecl-mcrypt &&\
  (deluser "$(grep ':33:' /etc/passwd | awk -F ':' '{print $1}')" || true) &&\
  (delgroup "$(grep '^www-data:' /etc/group | awk -F ':' '{print $1}')" || true) &&\
  mkdir /var/www &&\
  addgroup -g 33 www-data &&\
  adduser -D -u 33 -G www-data -s /sbin/nologin -H -h /var/www www-data &&\
  chown -R www-data:www-data /var/www &&\
  ln -sf /usr/bin/php83 /usr/bin/php &&\
  echo 'include=/etc/php83/php-fpm.d/www.inc' >> /etc/php83/php-fpm.d/www.conf

# add entrypoint script
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm83","-F","--fpm-config","/etc/php83/php-fpm.conf"]
