# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:latest
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# install typical php packages and then additional packages
RUN apk add --no-cache bind-tools imagemagick openssl php81 php81-bcmath php81-bz2 php81-ctype php81-curl php81-exif php81-fileinfo php81-gd php81-fpm php81-gettext php81-gmp php81-iconv php81-intl php81-imap php81-json php81-ldap php81-mbstring php81-mysqli php81-pecl-apcu php81-pecl-igbinary php81-pecl-imagick php81-pecl-memcached php81-pecl-redis php81-pdo php81-pdo_mysql php81-opcache php81-pdo_pgsql php81-pgsql php81-pcntl php81-posix php81-simplexml php81-sysvsem php81-xml php81-xmlreader php81-xmlwriter php81-zip ssmtp wget whois &&\
  apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community php81-pecl-mcrypt &&\
  sed -i "s#listen = 127.0.0.1:9000#listen = /var/run/php/php-fpm81.sock#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#^user = nobody#user = www-data#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#^group = nobody#group = www-data#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.owner = nobody#listen.owner = www-data#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.group = nobody#listen.group = www-data#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.mode = 0660#listen.mode = 0660#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#^;env#env#g" /etc/php81/php-fpm.d/www.conf &&\
  sed -i "s#upload_max_filesize = 2M#upload_max_filesize = 8M#g" /etc/php81/php.ini &&\
  sed -i "s#^;opcache.enable=1#opcache.enable=1#g" /etc/php81/php.ini &&\
  sed -i "s#^;opcache.interned_strings_buffer=8#opcache.interned_strings_buffer=32#g" /etc/php81/php.ini &&\
  sed -i "s#^;opcache.max_accelerated_files=10000#opcache.max_accelerated_files=25000#g" /etc/php81/php.ini &&\
  sed -i "s#^;opcache.memory_consumption=128#opcache.memory_consumption=256#g" /etc/php81/php.ini &&\
  sed -i "s#^;opcache.save_comments=1#opcache.save_comments=1#g" /etc/php81/php.ini &&\
  sed -i "s#^;opcache.revalidate_freq=2#opcache.revalidate_freq=30#g" /etc/php81/php.ini &&\
  echo 'apc.enable_cli=1' >> /etc/php81/conf.d/apcu.ini &&\
  deluser "$(grep ':33:' /etc/passwd | awk -F ':' '{print $1}')" || true &&\
  delgroup "$(grep '^www-data:' /etc/group | awk -F ':' '{print $1}')" || true &&\
  mkdir /var/www &&\
  addgroup -g 33 www-data &&\
  adduser -D -u 33 -G www-data -s /sbin/nologin -H -h /var/www www-data &&\
  chown -R www-data:www-data /var/www &&\
  ln -s /usr/bin/php81 /usr/bin/php

# add entrypoint script
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm81","-F","--fpm-config","/etc/php81/php-fpm.conf"]
