# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:latest
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# install typical php packages and then additional packages
RUN apk add --no-cache bind-tools imagemagick imagemagick-svg openssl php82 php82-bcmath php82-bz2 php82-ctype php82-curl php82-exif php82-fileinfo php82-gd php82-fpm php82-gettext php82-gmp php82-iconv php82-intl php82-imap php82-json php82-ldap php82-mbstring php82-mysqli php82-opcache php82-pecl-apcu php82-pecl-igbinary php82-pecl-imagick php82-pecl-mcrypt php82-pecl-memcached php82-pecl-redis php82-pdo php82-pdo_mysql php82-pdo_pgsql php82-phar php82-pgsql php82-pcntl php82-posix php82-simplexml php82-sodium php82-sysvsem php82-xml php82-xmlreader php82-xmlwriter php82-zip ssmtp wget whois &&\
  sed -i "s#listen = 127.0.0.1:9000#listen = /var/run/php/php-fpm82.sock#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#^user = nobody#user = www-data#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#^group = nobody#group = www-data#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.owner = nobody#listen.owner = www-data#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.group = nobody#listen.group = www-data#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#^;listen.mode = 0660#listen.mode = 0660#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#^;env#env#g" /etc/php82/php-fpm.d/www.conf &&\
  sed -i "s#upload_max_filesize = 2M#upload_max_filesize = 8M#g" /etc/php82/php.ini &&\
  sed -i "s#^;opcache.enable=1#opcache.enable=1#g" /etc/php82/php.ini &&\
  sed -i "s#^;opcache.interned_strings_buffer=8#opcache.interned_strings_buffer=32#g" /etc/php82/php.ini &&\
  sed -i "s#^;opcache.max_accelerated_files=10000#opcache.max_accelerated_files=25000#g" /etc/php82/php.ini &&\
  sed -i "s#^;opcache.memory_consumption=128#opcache.memory_consumption=256#g" /etc/php82/php.ini &&\
  sed -i "s#^;opcache.save_comments=1#opcache.save_comments=1#g" /etc/php82/php.ini &&\
  sed -i "s#^;opcache.revalidate_freq=2#opcache.revalidate_freq=30#g" /etc/php82/php.ini &&\
  sed -i "s#^output_buffering = 4096#output_buffering = Off#g" /etc/php82/php.ini &&\
  echo 'apc.enable_cli=1' >> /etc/php82/conf.d/apcu.ini &&\
  (deluser "$(grep ':33:' /etc/passwd | awk -F ':' '{print $1}')" || true) &&\
  (delgroup "$(grep '^www-data:' /etc/group | awk -F ':' '{print $1}')" || true) &&\
  mkdir /var/www &&\
  addgroup -g 33 www-data &&\
  adduser -D -u 33 -G www-data -s /sbin/nologin -H -h /var/www www-data &&\
  chown -R www-data:www-data /var/www &&\
  ln -sf /usr/bin/php82 /usr/bin/php

# add entrypoint script
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm82","-F","--fpm-config","/etc/php82/php-fpm.conf"]
