# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:3.16
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

# install typical php packages and then additional packages
RUN apk add --no-cache bash bind-tools imagemagick openssl php8 php8-bcmath php8-bz2 php8-ctype php8-curl php8-exif php8-fileinfo php8-gd php8-fpm php8-gettext php8-gmp php8-iconv php8-intl php8-imap php8-json php8-ldap php8-mbstring php8-mysqli php8-opcache php8-pecl-apcu php8-pecl-igbinary php8-pecl-imagick php8-pecl-mcrypt php8-pecl-memcached php8-pecl-redis php8-pdo php8-pdo_mysql php8-pdo_pgsql php8-pgsql php8-phar php8-pcntl php8-posix php8-simplexml php8-sodium php8-sysvsem php8-xml php8-xmlreader php8-xmlwriter php8-zip ssmtp wget whois &&\
  (deluser "$(grep ':33:' /etc/passwd | awk -F ':' '{print $1}')" || true) &&\
  (delgroup "$(grep '^www-data:' /etc/group | awk -F ':' '{print $1}')" || true) &&\
  mkdir /var/www &&\
  addgroup -g 33 www-data &&\
  adduser -D -u 33 -G www-data -s /sbin/nologin -H -h /var/www www-data &&\
  chown -R www-data:www-data /var/www &&\
  ln -sf /usr/bin/php8 /usr/bin/php &&\
  echo 'include=/etc/php8/php-fpm.d/www.inc' >> /etc/php8/php-fpm.d/www.conf

# add entrypoint script
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/php-fpm8","-F","--fpm-config","/etc/php8/php-fpm.conf"]
